name: neural
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python>=3.7.6
  - numpy
  - pytorch>=1.6.0
  - torchvision
  - tensorboard
  - cleverhans
  - easydict
  - setuptools
